### ISSUE TITLE
bluez-tools required for btmgmt

### ISSUE THREAD

**Issue by bobbybobbypangang** [kawasaki/bluepy-scratch-link#11]
In order to use btmgmt (on Arch at least) the bluez-tools package is required. It would be helpful to add this to the readme.

**Comment by kawasaki** [comment]
@bobbybobbypangang Thanks for the notice. I missed that the requirement.

I think the Arch package required is [bluez-utils](https://www.archlinux.org/packages/extra/x86_64/bluez-utils/). Will add that to the README. As for Ubuntu, bluez package looks including btmgmt.

**Comment by kawasaki** [comment]
Have added bluez-utils to the README. Thanks!
