### ISSUE TITLE
connect to lego wedo2

### ISSUE THREAD

**Issue by zhaowe** [kawasaki/bluepy-scratch-link#12]
device: LPF2 Smart Hub 2 I/O
scratch-link output:

    BLE service not found: [{'services': ['00001523-1212-efde-1523-785feabcd123']}]. Check BLE device.

While I run it with -d, the output is

    adtype 128b: None
    adtype 16b: None

I add code in scratch_link.py as below:

```python
    def matches(self, dev, filters):
        """
        Check if the found BLE device mathces the filters Scracth specifies.
        """
        logger.debug(f"in matches {dev} {filters}")
        dev_data = dev.getScanData()
        logger.debug(f"dev data: {dev_data}")
```
and run it with -d. I see the service value is in the Incomplete List of 128-bit Service Class UUIDs. So, I add codes as below

```python
                    service_class_uuid = dev.getValueText(self.ADTYPE_COMP_128B)
                    logger.debug(f"adtype 128b: {service_class_uuid}")
                    if not service_class_uuid:
                        service_class_uuid = dev.getValueText(self.ADTYPE_INCOMP_128B)
                        logger.debug(f"adtype incomp 128b: {service_class_uuid}")
                        if not service_class_uuid:
                            service_class_uuid = dev.getValueText(self.ADTYPE_COMP_16B)
                            logger.debug(f"adtype 16b: {service_class_uuid}")
                            if not service_class_uuid:
                                continue
```

It works! The set-color command sended from scratch run in the wedo2 controller perfectly.

**Comment by kawasaki** [comment]
@zhaowe Thank you so much for sharing your work. It is great to hear that now Lego WeDo2 is working!  I will try to integrate your code changes to the master branch when I have time, probably next week end. Thanks!

**Comment by kawasaki** [comment]
@zhaowe I have pushed a change to the bluepy-scratch-link master branch. The change is different from yours to make code cleaner, but I believe it works for Lego Wedo 2.0. If you have chance, please give it a try. Thanks!
