### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by mdevel1** [kawasaki/bluepy-scratch-link#2]
I've found your project while reading https://github.com/LLK/scratch-link/issues/84
Unfortunately I'm not able to use or read your code unless it's licensed.
Please read https://choosealicense.com/ and select one for your project. If you want to help in integrating your solution into scratch-link (if possible), you should follow their choice found here: https://github.com/LLK/scratch-link/blob/develop/LICENSE

**Comment by kawasaki** [comment]
Hi @mdevel1, thank you for the notice and request. I chose same license as scratch-link, and added LICENSE file to the bluepy-scratch-link repo. Wish the script helps.
