### ISSUE TITLE
Allow local server certificate in Google Chrome

### ISSUE THREAD

**Issue by ngammarano** [kawasaki/bluepy-scratch-link#3]
I think a way of allowing a local server certificate in Google Chrome is to type the bypass sequence "thisisunsafe" in https://device-manager.scratch.mit.edu:20110/. This should be required only the first time to access.

**Comment by jazzpecq** [comment]
The following patch includes changes to README adding instructions for Chrome browser.

[chrome_support_patch.txt](https://github.com/kawasaki/bluepy-scratch-link/files/4077556/chrome_support_patch.txt)

**Comment by kawasaki** [comment]
@ngammarano Wow, I didn't know that special key sequence. Thanks!
@jazzpecq Thank you for the patch! I applied that to the master.

Now I can play micro:bit and Scratch with Chrome :)
